version: "3.7"

services:
  database:
    image: postgres:alpine
    container_name: database_fin_api
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=fin_api
  app:
    build: .
    container_name: fin_api
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database
